// generated by stringer -type=apiVersion; DO NOT EDIT

package gimlet

import "fmt"

const _apiVersion_name = "NoneV1V2V3V4V5V6V7V8V9V10v11v12"

var _apiVersion_index = [...]uint8{0, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 25, 28, 31}

func (i apiVersion) String() string {
	i -= 1
	if i < 0 || i >= apiVersion(len(_apiVersion_index)-1) {
		return fmt.Sprintf("apiVersion(%d)", i+1)
	}
	return _apiVersion_name[_apiVersion_index[i]:_apiVersion_index[i+1]]
}
